var WORD_DICTIONARY = [
  { "baseWord": "november", "videoUrl": "november.mp4", "aliases": ["month"] },
  { "baseWord": "toilet", "videoUrl": "toilet.mp4", "aliases": ["washroom", "bathroom"] },
  { "baseWord": "silver", "videoUrl": "silver.mp4", "aliases": ["color"] },
  { "baseWord": "weekend", "videoUrl": "weekend.mp4", "aliases": ["saturday", "sunday"] },
  { "baseWord": "reminder", "videoUrl": "reminder.mp4", "aliases": ["remind"] },
  { "baseWord": "it", "videoUrl": "it.mp4", "aliases": [] },
  { "baseWord": "ruler", "videoUrl": "ruler.mp4", "aliases": ["scale"] },
  { "baseWord": "receipt", "videoUrl": "receipt.mp4", "aliases": ["bill"] },
  { "baseWord": "upload", "videoUrl": "upload.mp4", "aliases": [] },
  { "baseWord": "four", "videoUrl": "four.mp4", "aliases": ["4"] },
  { "baseWord": "file", "videoUrl": "file.mp4", "aliases": ["document"] },
  { "baseWord": "assign", "videoUrl": "assign.mp4", "aliases": ["assignment"] },
  { "baseWord": "hole punch", "videoUrl": "hole-punch.mp4", "aliases": ["punch"] },
  { "baseWord": "sunday", "videoUrl": "sunday.mp4", "aliases": [] },
  { "baseWord": "politics", "videoUrl": "politics.mp4", "aliases": ["political"] },
  { "baseWord": "come", "videoUrl": "come.mp4", "aliases": ["arrive"] },
  { "baseWord": "download", "videoUrl": "download.mp4", "aliases": [] },
  { "baseWord": "teams", "videoUrl": "teams.mp4", "aliases": ["microsoft teams"] },
  { "baseWord": "money", "videoUrl": "money.mp4", "aliases": ["cash", "rupee", "funds"] },
  { "baseWord": "white", "videoUrl": "white.mp4", "aliases": ["color"] },
  { "baseWord": "twenty", "videoUrl": "twenty.mp4", "aliases": ["20"] },
  { "baseWord": "winter", "videoUrl": "winter.mp4", "aliases": ["cold"] },
  { "baseWord": "seven", "videoUrl": "seven.mp4", "aliases": ["7"] },
  { "baseWord": "powerpoint", "videoUrl": "powerpoint.mp4", "aliases": ["ppt"] },
  { "baseWord": "on time", "videoUrl": "on-time.mp4", "aliases": ["punctual"] },
  { "baseWord": "laptop", "videoUrl": "laptop.mp4", "aliases": ["computer"] },
  { "baseWord": "classroom", "videoUrl": "classroom.mp4", "aliases": ["class"] },
  { "baseWord": "decide", "videoUrl": "decide.mp4", "aliases": ["decision"] },
  { "baseWord": "hurt", "videoUrl": "hurt.mp4", "aliases": ["pain"] },
  { "baseWord": "yes", "videoUrl": "yes.mp4", "aliases": ["ok", "okay"] },
  { "baseWord": "photocopy", "videoUrl": "photocopy.mp4", "aliases": ["xerox"] },
  { "baseWord": "facebook", "videoUrl": "facebook.mp4", "aliases": ["fb"] },
  { "baseWord": "meaning", "videoUrl": "meaning.mp4", "aliases": ["mean"] },
  { "baseWord": "ai", "videoUrl": "ai.mp4", "aliases": ["artificial intelligence"] },
  { "baseWord": "explain", "videoUrl": "explain.mp4", "aliases": ["explanation"] },
  { "baseWord": "fifteen", "videoUrl": "fifteen.mp4", "aliases": ["15"] },
  { "baseWord": "send", "videoUrl": "send.mp4", "aliases": ["mail"] },
  { "baseWord": "instagram", "videoUrl": "instagram.mp4", "aliases": ["ig"] },
  { "baseWord": "schedule", "videoUrl": "schedule.mp4", "aliases": ["plan"] },
  { "baseWord": "record", "videoUrl": "record.mp4", "aliases": [] },
  { "baseWord": "edit", "videoUrl": "edit.mp4", "aliases": ["change"] },
  { "baseWord": "august", "videoUrl": "august.mp4", "aliases": ["month"] },
  { "baseWord": "dark color", "videoUrl": "dark-color.mp4", "aliases": [] },
  { "baseWord": "red", "videoUrl": "red.mp4", "aliases": ["color"] },
  { "baseWord": "type", "videoUrl": "type.mp4", "aliases": ["typing"] },
  { "baseWord": "employee", "videoUrl": "employee.mp4", "aliases": ["staff", "worker"] },
  { "baseWord": "summer", "videoUrl": "summer.mp4", "aliases": ["hot"] },
  { "baseWord": "twelve", "videoUrl": "twelve.mp4", "aliases": ["12"] },
  { "baseWord": "again", "videoUrl": "again.mp4", "aliases": ["repeat"] },
  { "baseWord": "hearing", "videoUrl": "hearing.mp4", "aliases": ["listen"] },
  { "baseWord": "request", "videoUrl": "request.mp4", "aliases": ["please"] },
  { "baseWord": "one drive", "videoUrl": "one-drive.mp4", "aliases": ["cloud"] },
  { "baseWord": "trainer", "videoUrl": "trainer.mp4", "aliases": ["coach", "teacher"] },
  { "baseWord": "meeting room", "videoUrl": "meeting-room.mp4", "aliases": ["conference room"] },
  { "baseWord": "cpu", "videoUrl": "cpu.mp4", "aliases": ["computer"] },
  { "baseWord": "color", "videoUrl": "color.mp4", "aliases": ["colour"] },
  { "baseWord": "month", "videoUrl": "month.mp4", "aliases": [] },
  { "baseWord": "today", "videoUrl": "today.mp4", "aliases": ["now"] },
  { "baseWord": "approve", "videoUrl": "approve.mp4", "aliases": ["approval"] },
  { "baseWord": "pink", "videoUrl": "pink.mp4", "aliases": ["color"] },
  { "baseWord": "box cutter", "videoUrl": "box-cutter.mp4", "aliases": ["cutter"] },
  { "baseWord": "complaint", "videoUrl": "complaint.mp4", "aliases": ["complain"] },
  { "baseWord": "tuesday", "videoUrl": "tuesday.mp4", "aliases": [] },
  { "baseWord": "important", "videoUrl": "important.mp4", "aliases": ["urgent"] },
  { "baseWord": "car", "videoUrl": "car.mp4", "aliases": ["vehicle"] },
  { "baseWord": "marker", "videoUrl": "marker.mp4", "aliases": ["pen"] },
  { "baseWord": "visitor", "videoUrl": "visitor.mp4", "aliases": ["guest"] },
  { "baseWord": "studio", "videoUrl": "studio.mp4", "aliases": [] },
  { "baseWord": "need required import", "videoUrl": "need-required-import.mp4", "aliases": ["need", "require", "important"] },
  { "baseWord": "repeat", "videoUrl": "repeat.mp4", "aliases": ["again"] },
  { "baseWord": "education", "videoUrl": "education.mp4", "aliases": ["study", "learn"] },
  { "baseWord": "drink", "videoUrl": "drink.mp4", "aliases": ["water", "beverage"] },
  { "baseWord": "duration", "videoUrl": "duration.mp4", "aliases": ["time"] },
  { "baseWord": "school", "videoUrl": "school.mp4", "aliases": ["college"] },
  { "baseWord": "jump", "videoUrl": "jump.mp4", "aliases": [] },
  { "baseWord": "print", "videoUrl": "print.mp4", "aliases": ["printer"] },
  { "baseWord": "mouse", "videoUrl": "mouse.mp4", "aliases": ["computer mouse"] },
  { "baseWord": "camera", "videoUrl": "camera.mp4", "aliases": ["photo"] },
  { "baseWord": "finance dept 2", "videoUrl": "finance-dept-2.mp4", "aliases": ["finance", "accounts"] },
  { "baseWord": "webcam", "videoUrl": "webcam.mp4", "aliases": ["camera"] },
  { "baseWord": "ten", "videoUrl": "ten.mp4", "aliases": ["10"] },
  { "baseWord": "kolibri", "videoUrl": "kolibri.mp4", "aliases": [] },
  { "baseWord": "think", "videoUrl": "think.mp4", "aliases": ["thought"] },
  { "baseWord": "please", "videoUrl": "please.mp4", "aliases": ["kindly"] },
  { "baseWord": "dont understand", "videoUrl": "dont-understand.mp4", "aliases": ["confused"] },
  { "baseWord": "assistant", "videoUrl": "assistant.mp4", "aliases": ["helper"] },
  { "baseWord": "pending", "videoUrl": "pending.mp4", "aliases": ["waiting"] },
  { "baseWord": "sorry", "videoUrl": "sorry.mp4", "aliases": ["apology"] },
  { "baseWord": "missing", "videoUrl": "missing.mp4", "aliases": ["lost"] },
  { "baseWord": "handfree", "videoUrl": "handfree.mp4", "aliases": ["earphones"] },
  { "baseWord": "march", "videoUrl": "march.mp4", "aliases": ["month"] },
  { "baseWord": "hate", "videoUrl": "hate.mp4", "aliases": ["dislike"] },
  { "baseWord": "what", "videoUrl": "what.mp4", "aliases": ["kya"] },
  { "baseWord": "monday", "videoUrl": "monday.mp4", "aliases": [] },
  { "baseWord": "director", "videoUrl": "director.mp4", "aliases": ["boss"] },
  { "baseWord": "saturday", "videoUrl": "saturday.mp4", "aliases": [] },
  { "baseWord": "lakh", "videoUrl": "lakh.mp4", "aliases": ["100000"] },
  { "baseWord": "pen", "videoUrl": "pen.mp4", "aliases": ["write"] },
  { "baseWord": "headset", "videoUrl": "headset.mp4", "aliases": ["headphones"] },
  { "baseWord": "folder", "videoUrl": "folder.mp4", "aliases": ["file"] },
  { "baseWord": "parents", "videoUrl": "parents.mp4", "aliases": ["mother", "father"] },
  { "baseWord": "computer 2", "videoUrl": "computer-2.mp4", "aliases": ["pc"] },
  { "baseWord": "overtime", "videoUrl": "overtime.mp4", "aliases": ["extra time"] },
  { "baseWord": "order", "videoUrl": "order.mp4", "aliases": ["command"] },
  { "baseWord": "ready", "videoUrl": "ready.mp4", "aliases": ["prepared"] },
  { "baseWord": "workshop", "videoUrl": "workshop.mp4", "aliases": ["training"] },
  { "baseWord": "report", "videoUrl": "report.mp4", "aliases": [] },
  { "baseWord": "note pad", "videoUrl": "note-pad.mp4", "aliases": ["notebook"] },
  { "baseWord": "attendance", "videoUrl": "attendance.mp4", "aliases": ["present"] },
  { "baseWord": "week", "videoUrl": "week.mp4", "aliases": [] },
  { "baseWord": "deaf", "videoUrl": "deaf.mp4", "aliases": [] },
  { "baseWord": "question 1", "videoUrl": "question-1.mp4", "aliases": ["query", "ask"] },
  { "baseWord": "january", "videoUrl": "january.mp4", "aliases": ["month"] },
  { "baseWord": "leader", "videoUrl": "leader.mp4", "aliases": ["captain"] },
  { "baseWord": "curriculum", "videoUrl": "curriculum.mp4", "aliases": ["syllabus"] },
  { "baseWord": "calender", "videoUrl": "calender.mp4", "aliases": ["calendar"] },
  { "baseWord": "postpone", "videoUrl": "postpone.mp4", "aliases": ["delay"] },
  { "baseWord": "april", "videoUrl": "april.mp4", "aliases": ["month"] },
  { "baseWord": "salary slip", "videoUrl": "salary-slip.mp4", "aliases": ["payslip"] },
  { "baseWord": "delete", "videoUrl": "delete.mp4", "aliases": ["remove"] },
  { "baseWord": "late", "videoUrl": "late.mp4", "aliases": ["not on time"] },
  { "baseWord": "booking", "videoUrl": "booking.mp4", "aliases": ["reservation"] },
  { "baseWord": "july", "videoUrl": "july.mp4", "aliases": ["month"] },
  { "baseWord": "sixteen", "videoUrl": "sixteen.mp4", "aliases": ["16"] },
  { "baseWord": "admin", "videoUrl": "admin.mp4", "aliases": ["administration"] },
  { "baseWord": "radiant work force", "videoUrl": "radiant-work-force.mp4", "aliases": [] },
  { "baseWord": "whatsapp", "videoUrl": "whatsapp.mp4", "aliases": [] },
  { "baseWord": "prioity", "videoUrl": "prioity.mp4", "aliases": ["priority", "important"] },
  { "baseWord": "manager", "videoUrl": "manager.mp4", "aliases": ["boss"] },
  { "baseWord": "headphone", "videoUrl": "headphone.mp4", "aliases": ["headset"] },
  { "baseWord": "tomorrow", "videoUrl": "tomorrow.mp4", "aliases": ["next day"] },
  { "baseWord": "confirm", "videoUrl": "confirm.mp4", "aliases": ["confirm"] },
  { "baseWord": "have has", "videoUrl": "have-has.mp4", "aliases": ["possession"] },
  { "baseWord": "three", "videoUrl": "three.mp4", "aliases": ["3"] },
  { "baseWord": "million", "videoUrl": "million.mp4", "aliases": ["1000000"] },
  { "baseWord": "usb", "videoUrl": "usb.mp4", "aliases": ["flash drive"] },
  { "baseWord": "stop", "videoUrl": "stop.mp4", "aliases": ["halt"] },
  { "baseWord": "enjoy", "videoUrl": "enjoy.mp4", "aliases": ["happy", "fun"] },
  { "baseWord": "may", "videoUrl": "may.mp4", "aliases": ["month"] },
  { "baseWord": "appointment", "videoUrl": "appointment.mp4", "aliases": ["meeting"] },
  { "baseWord": "hello", "videoUrl": "hello.mp4", "aliases": ["hi", "hey"] },
  { "baseWord": "whiteboard", "videoUrl": "whiteboard.mp4", "aliases": ["board"] },
  { "baseWord": "grey", "videoUrl": "grey.mp4", "aliases": ["gray", "color"] },
  { "baseWord": "id card", "videoUrl": "id-card.mp4", "aliases": ["identification"] },
  { "baseWord": "before previous", "videoUrl": "before-previous.mp4", "aliases": ["before"] },
  { "baseWord": "see", "videoUrl": "see.mp4", "aliases": ["look", "watch"] },
  { "baseWord": "why", "videoUrl": "why.mp4", "aliases": ["reason"] },
  { "baseWord": "projector", "videoUrl": "projector.mp4", "aliases": [] },
  { "baseWord": "no", "videoUrl": "no.mp4", "aliases": ["not", "nahi"] },
  { "baseWord": "eleven", "videoUrl": "eleven.mp4", "aliases": ["11"] },
  { "baseWord": "appreciate", "videoUrl": "appreciate.mp4", "aliases": ["thanks", "good"] },
  { "baseWord": "september", "videoUrl": "september.mp4", "aliases": ["month"] },
  { "baseWord": "form", "videoUrl": "form.mp4", "aliases": ["document"] },
  { "baseWord": "eighteen", "videoUrl": "eighteen.mp4", "aliases": ["18"] },
  { "baseWord": "guidelines rules", "videoUrl": "guidelines-rules.mp4", "aliases": ["rules", "policy"] },
  { "baseWord": "different", "videoUrl": "different.mp4", "aliases": ["unlike"] },
  { "baseWord": "want", "videoUrl": "want.mp4", "aliases": ["need"] },
  { "baseWord": "name", "videoUrl": "name.mp4", "aliases": [] },
  { "baseWord": "one", "videoUrl": "one.mp4", "aliases": ["1"] },
  { "baseWord": "thirteen", "videoUrl": "thirteen.mp4", "aliases": ["13"] },
  { "baseWord": "nineteen", "videoUrl": "nineteen.mp4", "aliases": ["19"] },
  { "baseWord": "when", "videoUrl": "when.mp4", "aliases": ["time"] },
  { "baseWord": "june", "videoUrl": "june.mp4", "aliases": ["month"] },
  { "baseWord": "night", "videoUrl": "night.mp4", "aliases": ["dark"] },
  { "baseWord": "cabinet cupboard", "videoUrl": "cabinet-cupboard.mp4", "aliases": ["cupboard", "cabinet"] },
  { "baseWord": "slip", "videoUrl": "slip.mp4", "aliases": ["paper"] },
  { "baseWord": "lamination", "videoUrl": "lamination.mp4", "aliases": [] },
  { "baseWord": "sit", "videoUrl": "sit.mp4", "aliases": ["seat"] },
  { "baseWord": "time", "videoUrl": "time.mp4", "aliases": ["clock"] },
  { "baseWord": "minute", "videoUrl": "minute.mp4", "aliases": ["time"] },
  { "baseWord": "signature", "videoUrl": "signature.mp4", "aliases": ["sign"] },
  { "baseWord": "color pencils", "videoUrl": "color-pencils.mp4", "aliases": ["pencils"] },
  { "baseWord": "free", "videoUrl": "free.mp4", "aliases": ["available"] },
  { "baseWord": "internet device", "videoUrl": "internet-device.mp4", "aliases": ["wifi", "modem"] },
  { "baseWord": "light color", "videoUrl": "light-color.mp4", "aliases": [] },
  { "baseWord": "stapler", "videoUrl": "stapler.mp4", "aliases": [] },
  { "baseWord": "wednesday", "videoUrl": "wednesday.mp4", "aliases": [] },
  { "baseWord": "october", "videoUrl": "october.mp4", "aliases": ["month"] },
  { "baseWord": "working hours", "videoUrl": "working-hours.mp4", "aliases": ["office hours"] },
  { "baseWord": "sky blue", "videoUrl": "sky-blue.mp4", "aliases": ["color"] },
  { "baseWord": "hr", "videoUrl": "hr.mp4", "aliases": ["human resources"] },
  { "baseWord": "lesson plan", "videoUrl": "lesson-plan.mp4", "aliases": ["plan"] },
  { "baseWord": "application", "videoUrl": "application.mp4", "aliases": ["app"] },
  { "baseWord": "typing", "videoUrl": "typing.mp4", "aliases": ["type"] },
  { "baseWord": "office", "videoUrl": "office.mp4", "aliases": ["work"] },
  { "baseWord": "evening", "videoUrl": "evening.mp4", "aliases": ["time"] },
  { "baseWord": "policy", "videoUrl": "policy.mp4", "aliases": ["rules"] },
  { "baseWord": "where", "videoUrl": "where.mp4", "aliases": ["location"] },
  { "baseWord": "eat", "videoUrl": "eat.mp4", "aliases": ["food", "meal"] },
  { "baseWord": "eraser", "videoUrl": "eraser.mp4", "aliases": ["remove"] },
  { "baseWord": "youtube", "videoUrl": "youtube.mp4", "aliases": ["yt"] },
  { "baseWord": "notebook", "videoUrl": "notebook.mp4", "aliases": ["book"] },
  { "baseWord": "year", "videoUrl": "year.mp4", "aliases": [] },
  { "baseWord": "original", "videoUrl": "original.mp4", "aliases": ["real"] },
  { "baseWord": "friday", "videoUrl": "friday.mp4", "aliases": ["juma"] },
  { "baseWord": "purple", "videoUrl": "purple.mp4", "aliases": ["color"] },
  { "baseWord": "wait", "videoUrl": "wait.mp4", "aliases": ["hold"] },
  { "baseWord": "hundred", "videoUrl": "hundred.mp4", "aliases": ["100"] },
  { "baseWord": "ballpoint pen", "videoUrl": "ballpoint-pen.mp4", "aliases": ["pen"] },
  { "baseWord": "five", "videoUrl": "five.mp4", "aliases": ["5"] },
  { "baseWord": "resources", "videoUrl": "resources.mp4", "aliases": [] },
  { "baseWord": "maroon", "videoUrl": "maroon.mp4", "aliases": ["color"] },
  { "baseWord": "cheque", "videoUrl": "cheque.mp4", "aliases": ["bank"] },
  { "baseWord": "seventeen", "videoUrl": "seventeen.mp4", "aliases": ["17"] },
  { "baseWord": "pay", "videoUrl": "pay.mp4", "aliases": ["salary", "money"] },
  { "baseWord": "meet", "videoUrl": "meet.mp4", "aliases": ["meeting"] },
  { "baseWord": "calculator", "videoUrl": "calculator.mp4", "aliases": ["math"] },
  { "baseWord": "website", "videoUrl": "website.mp4", "aliases": ["web"] },
  { "baseWord": "yesterday", "videoUrl": "yesterday.mp4", "aliases": ["past"] },
  { "baseWord": "certificate", "videoUrl": "certificate.mp4", "aliases": ["degree"] },
  { "baseWord": "close", "videoUrl": "close.mp4", "aliases": ["shut"] },
  { "baseWord": "stamp", "videoUrl": "stamp.mp4", "aliases": [] },
  { "baseWord": "previoys before", "videoUrl": "previoys-before.mp4", "aliases": ["before", "previous"] },
  { "baseWord": "cheque book", "videoUrl": "cheque-book.mp4", "aliases": ["bank"] },
  { "baseWord": "duster", "videoUrl": "duster.mp4", "aliases": ["clean"] },
  { "baseWord": "busy", "videoUrl": "busy.mp4", "aliases": ["working"] },
  { "baseWord": "excel", "videoUrl": "excel.mp4", "aliases": ["ms excel"] },
  { "baseWord": "green", "videoUrl": "green.mp4", "aliases": ["color"] },
  { "baseWord": "february", "videoUrl": "february.mp4", "aliases": ["month"] },
  { "baseWord": "canva", "videoUrl": "canva.mp4", "aliases": ["design"] },
  { "baseWord": "december", "videoUrl": "december.mp4", "aliases": ["month"] },
  { "baseWord": "computer", "videoUrl": "computer.mp4", "aliases": ["pc"] },
  { "baseWord": "trash bin", "videoUrl": "trash-bin.mp4", "aliases": ["dustbin", "trash"] },
  { "baseWord": "plastic", "videoUrl": "plastic.mp4", "aliases": [] },
  { "baseWord": "table", "videoUrl": "table.mp4", "aliases": ["desk"] },
  { "baseWord": "finish", "videoUrl": "finish.mp4", "aliases": ["done", "complete"] },
  { "baseWord": "thankyou", "videoUrl": "thankyou.mp4", "aliases": ["thanks", "thank you"] },
  { "baseWord": "knock", "videoUrl": "knock.mp4", "aliases": [] },
  { "baseWord": "thousand", "videoUrl": "thousand.mp4", "aliases": ["1000"] },
  { "baseWord": "now", "videoUrl": "now.mp4", "aliases": ["today"] },
  { "baseWord": "support", "videoUrl": "support.mp4", "aliases": ["help"] },
  { "baseWord": "wifi", "videoUrl": "wifi.mp4", "aliases": ["internet"] },
  { "baseWord": "orange", "videoUrl": "orange.mp4", "aliases": ["color"] },
  { "baseWord": "principal", "videoUrl": "principal.mp4", "aliases": ["headmaster", "boss"] },
  { "baseWord": "urgent immediately", "videoUrl": "urgent-immediately.mp4", "aliases": ["urgent", "immediately", "fast"] },
  { "baseWord": "tell", "videoUrl": "tell.mp4", "aliases": ["say"] },
  { "baseWord": "eight", "videoUrl": "eight.mp4", "aliases": ["8"] },
  { "baseWord": "sticky note", "videoUrl": "sticky-note.mp4", "aliases": ["note"] },
  { "baseWord": "help", "videoUrl": "help.mp4", "aliases": ["assist", "support"] },
  { "baseWord": "chair", "videoUrl": "chair.mp4", "aliases": ["seat"] },
  { "baseWord": "letter", "videoUrl": "letter.mp4", "aliases": ["mail"] },
  { "baseWord": "check", "videoUrl": "check.mp4", "aliases": ["verify"] },
  { "baseWord": "zoom", "videoUrl": "zoom.mp4", "aliases": ["meeting"] },
  { "baseWord": "later", "videoUrl": "later.mp4", "aliases": ["after"] },
  { "baseWord": "deadline", "videoUrl": "deadline.mp4", "aliases": ["limit"] },
  { "baseWord": "give", "videoUrl": "give.mp4", "aliases": ["provide"] },
  { "baseWord": "friend", "videoUrl": "friend.mp4", "aliases": ["buddy"] },
  { "baseWord": "information", "videoUrl": "information.mp4", "aliases": ["info"] },
  { "baseWord": "coordinator", "videoUrl": "coordinator.mp4", "aliases": ["manager"] },
  { "baseWord": "teacher", "videoUrl": "teacher.mp4", "aliases": ["sir", "ustad"] },
  { "baseWord": "submit", "videoUrl": "submit.mp4", "aliases": ["give"] },
  { "baseWord": "day", "videoUrl": "day.mp4", "aliases": [] },
  { "baseWord": "document", "videoUrl": "document.mp4", "aliases": ["file"] },
  { "baseWord": "thursday", "videoUrl": "thursday.mp4", "aliases": [] },
  { "baseWord": "ground", "videoUrl": "ground.mp4", "aliases": ["floor"] },
  { "baseWord": "yellow", "videoUrl": "yellow.mp4", "aliases": ["color"] },
  { "baseWord": "who", "videoUrl": "who.mp4", "aliases": [] },
  { "baseWord": "paper", "videoUrl": "paper.mp4", "aliases": [] },
  { "baseWord": "word", "videoUrl": "word.mp4", "aliases": [] },
  { "baseWord": "understand", "videoUrl": "understand.mp4", "aliases": ["comprehend"] },
  { "baseWord": "open", "videoUrl": "open.mp4", "aliases": ["unlock"] },
  { "baseWord": "laugh", "videoUrl": "laugh.mp4", "aliases": ["happy"] },
  { "baseWord": "fight", "videoUrl": "fight.mp4", "aliases": ["angry"] },
  { "baseWord": "fourteen", "videoUrl": "fourteen.mp4", "aliases": ["14"] },
  { "baseWord": "hour", "videoUrl": "hour.mp4", "aliases": ["time"] },
  { "baseWord": "afternoon", "videoUrl": "afternoon.mp4", "aliases": ["time"] },
  { "baseWord": "call sign 2", "videoUrl": "call-sign-2.mp4", "aliases": ["call"] },
  { "baseWord": "okay", "videoUrl": "okay.mp4", "aliases": ["ok", "yes"] },
  { "baseWord": "blue", "videoUrl": "blue.mp4", "aliases": ["color"] },
  { "baseWord": "scan", "videoUrl": "scan.mp4", "aliases": ["scanner"] },
  { "baseWord": "stand", "videoUrl": "stand.mp4", "aliases": ["up"] },
  { "baseWord": "brown", "videoUrl": "brown.mp4", "aliases": ["color"] },
  { "baseWord": "keyboard", "videoUrl": "keyboard.mp4", "aliases": ["typing"] },
  { "baseWord": "student", "videoUrl": "student.mp4", "aliases": ["pupil"] },
  { "baseWord": "morning", "videoUrl": "morning.mp4", "aliases": ["subah"] },
  { "baseWord": "day before yesterday", "videoUrl": "day-before-yesterday.mp4", "aliases": [] },
  { "baseWord": "two", "videoUrl": "two.mp4", "aliases": ["2"] },
  { "baseWord": "like", "videoUrl": "like.mp4", "aliases": ["love", "favourite"] },
  { "baseWord": "pay attention focus", "videoUrl": "pay-attention-focus.mp4", "aliases": ["focus", "attention"] },
  { "baseWord": "job", "videoUrl": "job.mp4", "aliases": ["work"] },
  { "baseWord": "delay", "videoUrl": "delay.mp4", "aliases": ["late"] },
  { "baseWord": "six", "videoUrl": "six.mp4", "aliases": ["6"] },
  { "baseWord": "book", "videoUrl": "book.mp4", "aliases": ["read"] },
  { "baseWord": "registration", "videoUrl": "registration.mp4", "aliases": ["register"] },
  { "baseWord": "gold", "videoUrl": "gold.mp4", "aliases": ["color"] },
  { "baseWord": "black", "videoUrl": "black.mp4", "aliases": ["color"] },
  { "baseWord": "answer 1", "videoUrl": "answer-1.mp4", "aliases": ["reply", "jawab"] },
  { "baseWord": "nine", "videoUrl": "nine.mp4", "aliases": ["9"] },
  { "baseWord": "crore", "videoUrl": "crore.mp4", "aliases": ["10000000"] },
  { "baseWord": "day after tomorrow", "videoUrl": "day-after-tomorrow.mp4", "aliases": [] },
  { "baseWord": "work", "videoUrl": "work.mp4", "aliases": ["job"] },
  { "baseWord": "how", "videoUrl": "how.mp4", "aliases": [] },
  { "baseWord": "commnuication", "videoUrl": "commnuication.mp4", "aliases": ["communication", "talk"] },
  { "baseWord": "kitchen", "videoUrl": "kitchen.mp4", "aliases": ["cook"] },
  { "baseWord": "interpreter", "videoUrl": "interpreter.mp4", "aliases": ["translator"] },
  { "baseWord": "sharpner", "videoUrl": "sharpner.mp4", "aliases": ["pencil"] },
  { "baseWord": "stationery", "videoUrl": "stationery.mp4", "aliases": ["office supplies"] }
];
